#!/usr/bin/env bash
set -Eeuo pipefail

: "${VIROS_QEMU_X86_64:?}"
: "${VIROS_X86_LD_ROOT:?}"
: "${VIROS_CROSS_REAL_BIN:?}"

name=${0##*/}
tool=${name#powerpc-linux-}
real="$VIROS_CROSS_REAL_BIN/powerpc-linux-$tool"

if [[ "$tool" == gcc ]]; then
    real="$VIROS_CROSS_REAL_BIN/powerpc-linux-gcc.br_real"
    exec "$VIROS_QEMU_X86_64" -L "$VIROS_X86_LD_ROOT" "$real" \
        -wrapper "$VIROS_QEMU_X86_64,-L,$VIROS_X86_LD_ROOT" "$@"
fi

exec "$VIROS_QEMU_X86_64" -L "$VIROS_X86_LD_ROOT" "$real" "$@"
