//! The frame driver (ASSEMBLY.md §4 lifecycle): a `refPrefix` full-state plus a
//! geometric delta stack, advanced per written layer and sealed into a fresh
//! `refPrefix` when a frame is written.
//!
//! This is the thin assembly over the parts already built and tested:
//!
//! - a new layer's delta is generated by [`layer::delta_multi_lane_stacked`],
//!   reading the current state straight from `refPrefix + stack` (no
//!   materialized union) and matching variants by `(mode, oid)`;
//! - the delta is pushed on the [`GeoStack`], compacted with `compose_stream`
//!   (delta ∘ delta — holes survive);
//! - a read between seals materializes `overlay_full(refPrefix, collapse(stack))`
//!   only when a full union is actually needed (a read or a seal);
//! - a seal replaces `refPrefix` with that union (holes dissolve to removals)
//!   and clears the stack.
//!
//! The lane trees of the current state are kept alongside so the next delta can
//! read a variant's oid for free (§3) — never by hashing stored content.

use crate::geostack::GeoStack;
use crate::layer::{self, LaneTree};

/// delta ∘ delta merge for the stack: `compose_stream(lower, upper)`.
fn compose(lower: Vec<u8>, upper: Vec<u8>) -> Vec<u8> {
    let mut out = Vec::new();
    depot::stream::compose_stream(&lower, &upper, &mut out).expect("compose_stream on canonical layers");
    // A fully-annihilating merge can yield nothing; keep the layer decodable.
    if out.is_empty() {
        layer::empty_union()
    } else {
        out
    }
}

fn size(l: &Vec<u8>) -> u64 {
    l.len() as u64
}

/// One shard's frame: the sealed base full-state and the live delta stack over
/// it, plus the current lane trees (for oid lookup on the next advance).
pub struct Frame {
    refprefix: Vec<u8>,
    stack: GeoStack<Vec<u8>>,
    lanes: Vec<LaneTree>,
}

impl Frame {
    /// Seed a frame from the initial lanes: the `refPrefix` is their union,
    /// the stack empty.
    pub fn seed(lanes: Vec<LaneTree>) -> Self {
        Frame { refprefix: layer::encode_union(&lanes), stack: GeoStack::new(), lanes }
    }

    /// Advance to a new set of lane trees (a written layer): generate the delta
    /// against the current state and push it on the geometric stack.
    pub fn advance(&mut self, new_lanes: Vec<LaneTree>) {
        let delta =
            layer::delta_multi_lane_stacked(&self.refprefix, self.stack.layers(), &self.lanes, &new_lanes);
        self.stack.push(delta, size, compose);
        self.lanes = new_lanes;
    }

    /// Materialize the current full union (`refPrefix` + live stack). Only
    /// needed for a read or a seal — never to generate the next delta.
    pub fn union(&self) -> Vec<u8> {
        let layers = self.stack.layers();
        if layers.is_empty() {
            return self.refprefix.clone();
        }
        let mut combined = layers[0].clone();
        for l in &layers[1..] {
            combined = compose(combined, l.clone());
        }
        let mut out = Vec::new();
        depot::stream::overlay_full(&self.refprefix, &combined, &mut out)
            .expect("overlay_full on canonical layers");
        // overlay can emit nothing when the whole tree is removed; keep the
        // full-state decodable.
        if out.is_empty() {
            layer::empty_union()
        } else {
            out
        }
    }

    /// Write the frame: collapse the whole stack into a new `refPrefix`
    /// (holes dissolve to removals) and clear the stack.
    pub fn seal(&mut self) {
        self.refprefix = self.union();
        self.stack = GeoStack::new();
    }

    /// The number of live lanes.
    pub fn n_lanes(&self) -> u32 {
        self.lanes.len() as u32
    }

    /// The number of live delta layers on the stack.
    pub fn stack_len(&self) -> usize {
        self.stack.len()
    }

    /// Reconstruct lane `lane`'s git tree oid from the current union — the
    /// SHA-exact reconstruction (§6).
    pub fn reconstruct_tree_oid(&self, lane: u32) -> Result<String, depot::walk::DecodeError> {
        layer::reconstruct_lane_tree_oid(&self.union(), lane)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::layer::{LaneEntry, LaneTree, Mode};

    fn lane(entries: &[(&[u8], Mode, &[u8], &[u8])]) -> LaneTree {
        entries
            .iter()
            .map(|(p, m, oid, c)| {
                (p.to_vec(), LaneEntry { mode: *m, oid: oid.to_vec(), content: c.to_vec() })
            })
            .collect()
    }

    /// Every lane in the current state must reconstruct to the same tree oid as
    /// building it straight from its lane tree — proven after each advance and
    /// across a seal.
    fn assert_all_lanes(f: &Frame, lanes: &[LaneTree]) {
        for (j, t) in lanes.iter().enumerate() {
            assert_eq!(
                f.reconstruct_tree_oid(j as u32).unwrap(),
                layer::lanetree_tree_oid(t).unwrap(),
                "lane {j} tree oid"
            );
        }
    }

    /// Drive a small multi-lane history through the frame driver — advances,
    /// content/mode changes, a per-lane add and remove, a seal mid-stream —
    /// and check SHA-exact reconstruction of every lane at every step.
    #[test]
    fn frame_lifecycle_is_sha_exact() {
        // Three lanes (three branch tips), sharing most files.
        let s0 = vec![
            lane(&[
                (b"README", Mode::File, b"r0", b"hi\n"),
                (b"src/main.rs", Mode::File, b"m0", b"fn main(){}\n"),
                (b"src/run.sh", Mode::Exec, b"x0", b"#!\n"),
            ]),
            lane(&[
                (b"README", Mode::File, b"r0", b"hi\n"),
                (b"src/main.rs", Mode::File, b"m1", b"fn main(){2}\n"),
                (b"src/run.sh", Mode::Exec, b"x0", b"#!\n"),
            ]),
            lane(&[
                (b"README", Mode::File, b"r0", b"hi\n"),
                (b"src/main.rs", Mode::File, b"m0", b"fn main(){}\n"),
                (b"link", Mode::Symlink, b"l0", b"README"),
            ]),
        ];
        let mut f = Frame::seed(s0.clone());
        assert_all_lanes(&f, &s0);

        // Lane 1 advances: README edited, run.sh loses +x (mode flip), a new file.
        let mut s1 = s0.clone();
        s1[1] = lane(&[
            (b"README", Mode::File, b"r1", b"hi there\n"),
            (b"src/main.rs", Mode::File, b"m1", b"fn main(){2}\n"),
            (b"src/run.sh", Mode::File, b"x1", b"#!\n"),
            (b"CHANGELOG", Mode::File, b"c0", b"- x\n"),
        ]);
        f.advance(s1.clone());
        assert_all_lanes(&f, &s1);

        // Lane 2 advances: link removed, main.rs changes to lane 1's version
        // (variants collapse), gitlink added.
        let mut s2 = s1.clone();
        s2[2] = lane(&[
            (b"README", Mode::File, b"r0", b"hi\n"),
            (b"src/main.rs", Mode::File, b"m1", b"fn main(){2}\n"),
            (b"dep", Mode::Gitlink, b"g0", b"0123456789abcdef0123456789abcdef01234567"),
        ]);
        f.advance(s2.clone());
        assert_all_lanes(&f, &s2);

        // Seal: collapse the stack into a fresh refPrefix; reconstruction must
        // still be exact and the stack empty.
        f.seal();
        assert_eq!(f.stack_len(), 0);
        assert_all_lanes(&f, &s2);

        // Advance again after the seal (exercises delta-over-fresh-refPrefix).
        let mut s3 = s2.clone();
        s3[0] = lane(&[
            (b"README", Mode::File, b"r2", b"hello\n"),
            (b"src/main.rs", Mode::File, b"m0", b"fn main(){}\n"),
            (b"src/run.sh", Mode::Exec, b"x0", b"#!\n"),
        ]);
        f.advance(s3.clone());
        assert_all_lanes(&f, &s3);
    }

    /// Randomized lifecycle: many lanes evolving over many advances with random
    /// content/mode/add/remove churn and occasional seals; every lane must
    /// reconstruct SHA-exact at every step, and seals must not change any oid.
    #[test]
    fn frame_lifecycle_randomized() {
        fn next(rng: &mut u64) -> u64 {
            *rng ^= *rng << 13;
            *rng ^= *rng >> 7;
            *rng ^= *rng << 17;
            *rng
        }
        let paths: [&[u8]; 6] = [b"a", b"d/x", b"d/y", b"d/e/f", b"README", b"z"];
        let modes = [Mode::File, Mode::Exec, Mode::Symlink];
        let gen_tree = |rng: &mut u64| -> LaneTree {
            let mut t = LaneTree::new();
            for p in paths {
                if next(rng) % 4 != 0 {
                    let mode = modes[(next(rng) % 3) as usize];
                    let c = vec![b'v', (next(rng) % 9) as u8 + b'0'];
                    // oid follows (mode, content) so identity is stable/shared.
                    let oid = [&[mode as u8][..], &c[..]].concat();
                    t.insert(p.to_vec(), LaneEntry { mode, oid, content: c });
                }
            }
            t
        };

        let mut rng = 0x0d15_ea5eu64;
        for _ in 0..120 {
            let n_lanes = 1 + (next(&mut rng) % 4) as usize;
            let mut lanes: Vec<LaneTree> = (0..n_lanes).map(|_| gen_tree(&mut rng)).collect();
            let mut f = Frame::seed(lanes.clone());
            assert_all_lanes(&f, &lanes);
            let steps = 1 + (next(&mut rng) % 6);
            for _ in 0..steps {
                // Advance one random lane to a fresh tree.
                let j = (next(&mut rng) % n_lanes as u64) as usize;
                lanes[j] = gen_tree(&mut rng);
                f.advance(lanes.clone());
                assert_all_lanes(&f, &lanes);
                if next(&mut rng) % 3 == 0 {
                    f.seal();
                    assert_all_lanes(&f, &lanes); // a seal preserves every oid
                }
            }
        }
    }
}
