:- module(brush_grammar, [brush_relation_grammar/1]).

/** <module> Brush shell language grammar

This module is a client of the generic grammar engine.  It contains shell
language knowledge as one immutable grammar value, but no parsing predicates.
The initial grammar deliberately covers only shell words; later checkpoints
will grow the same value into complete shell programs before any Brush consumer
uses it as an authority.
*/

brush_relation_grammar(
    grammar(
        source(text(utf8)), shell_program,
        [rule(shell_program,
              extras([ref(horizontal_space)], ref(command_list))),
         rule(horizontal_space,
              terminal(text(codepoint(chars(" \t\r"))),
                       presentation([meta(syntax, trivia),
                                     meta(description, whitespace)]))),
         rule(required_horizontal_space,
              repeat(1, unbounded,
                     terminal(text(codepoint(chars(" \t\r"))),
                              presentation([meta(syntax, trivia),
                                            meta(description, whitespace)])))),
         rule(command_list,
              seq([ref(and_or),
                   repeat(0, unbounded,
                          seq([ref(list_separator), ref(and_or)])),
                   optional(ref(list_separator))])),
         rule(list_separator,
              choice([literal(";", sequence,
                              presentation([meta(syntax, operator)])),
                      literal("\n", newline,
                              presentation([meta(syntax, operator)])),
                      lexical(
                          seq([literal("&", background,
                                       presentation([meta(syntax, operator)])),
                               not(literal("&", and_if_tail,
                                           presentation([])))]))])),
         rule(and_or,
              seq([ref(pipeline),
                   repeat(0, unbounded,
                          seq([ref(and_or_operator), ref(pipeline)]))])),
         rule(and_or_operator,
              choice([literal("&&", and_if,
                              presentation([meta(syntax, operator)])),
                      literal("||", or_if,
                              presentation([meta(syntax, operator)]))])),
         rule(pipeline,
              seq([optional(literal("!", negate,
                                    presentation([meta(syntax, keyword)]))),
                   ref(simple_command),
                   repeat(0, unbounded,
                          seq([lexical(
                                   seq([literal("|", pipe,
                                                presentation([meta(syntax, operator)])),
                                        not(literal("|", or_if_tail,
                                                    presentation([])))])),
                               ref(simple_command)]))])),
         rule(simple_command,
              lexical(
                  seq([ref(shell_word),
                       repeat(0, unbounded,
                              seq([ref(required_horizontal_space),
                                   ref(shell_word)]))]))),
         rule(shell_word,
              lexical(seq([repeat(1, unbounded, ref(word_part)),
                           not(ref(word_part))]))),
         rule(word_part,
              choice([ref(arithmetic_expansion),
                      ref(command_substitution),
                      ref(parameter_expansion),
                      ref(escape),
                      ref(single_quoted),
                      ref(double_quoted),
                      ref(unquoted_text)])),
         rule(unquoted_text,
              terminal(text(codepoint(except(" \t\r\n\\'\"$|&;()<>"))),
                       presentation([meta(syntax, word),
                                     meta(description, shell_word)]))),
         rule(escape,
              seq([literal("\\", escape,
                           presentation([meta(syntax, escape)])),
                   terminal(text(codepoint(any)),
                            presentation([meta(syntax, escaped),
                                          meta(description, escaped_codepoint)]))])),
         rule(single_quoted,
              seq([literal("'", quote_open,
                           presentation([meta(syntax, delimiter)])),
                   repeat(0, unbounded,
                          terminal(text(codepoint(except("'"))),
                                   presentation([meta(syntax, string)]))),
                   literal("'", quote_close,
                           presentation([meta(syntax, delimiter)]))])),
         rule(double_quoted,
              seq([literal("\"", quote_open,
                           presentation([meta(syntax, delimiter)])),
                   repeat(0, unbounded, ref(double_quoted_part)),
                   literal("\"", quote_close,
                           presentation([meta(syntax, delimiter)]))])),
         rule(double_quoted_part,
              choice([ref(arithmetic_expansion),
                      ref(command_substitution),
                      ref(parameter_expansion),
                      ref(escape),
                      terminal(text(codepoint(except("\"\\$"))),
                               presentation([meta(syntax, string)])),
                      ref(double_literal_dollar)])),
         rule(parameter_expansion,
              choice([ref(braced_parameter), ref(simple_parameter),
                      ref(special_parameter)])),
         rule(simple_parameter,
              seq([literal("$", parameter_sigil,
                           presentation([meta(syntax, variable)])),
                   terminal(text(codepoint(union([range(65, 90),
                                                  range(97, 122),
                                                  chars("_")]))),
                            presentation([meta(syntax, variable)])),
                   repeat(0, unbounded,
                          terminal(text(codepoint(union([range(65, 90),
                                                         range(97, 122),
                                                         range(48, 57),
                                                         chars("_")]))),
                                   presentation([meta(syntax, variable)]))),
                   not(terminal(text(codepoint(union([range(65, 90),
                                                       range(97, 122),
                                                       range(48, 57),
                                                       chars("_")]))),
                                presentation([])))])),
         rule(special_parameter,
              seq([literal("$", parameter_sigil,
                           presentation([meta(syntax, variable)])),
                   terminal(text(codepoint(chars("0123456789*?#$!-@"))),
                            presentation([meta(syntax, variable)]))])),
         rule(braced_parameter,
              seq([literal("${", parameter_open,
                           presentation([meta(syntax, delimiter)])),
                   repeat(1, unbounded,
                          terminal(text(codepoint(except("}"))),
                                   presentation([meta(syntax, variable)]))),
                   literal("}", parameter_close,
                           presentation([meta(syntax, delimiter)]))])),
         rule(command_substitution,
              seq([literal("$(", command_substitution_open,
                           presentation([meta(syntax, delimiter)])),
                   repeat(0, unbounded, ref(command_substitution_part)),
                   literal(")", command_substitution_close,
                           presentation([meta(syntax, delimiter)]))])),
         rule(command_substitution_part,
              choice([ref(arithmetic_expansion),
                      ref(command_substitution),
                      ref(parameter_expansion),
                      ref(escape),
                      ref(single_quoted),
                      ref(double_quoted),
                      terminal(text(codepoint(except("()\\'\"$"))),
                               presentation([meta(syntax, command)])),
                      ref(command_literal_dollar)])),
         rule(arithmetic_expansion,
              seq([literal("$((", arithmetic_open,
                           presentation([meta(syntax, delimiter)])),
                   repeat(0, unbounded, ref(arithmetic_part)),
                   literal("))", arithmetic_close,
                           presentation([meta(syntax, delimiter)]))])),
         rule(arithmetic_part,
              choice([ref(arithmetic_group),
                      ref(parameter_expansion),
                      terminal(text(codepoint(except("()$"))),
                               presentation([meta(syntax, arithmetic)])),
                      ref(arithmetic_literal_dollar)])),
         rule(arithmetic_group,
              seq([literal("(", arithmetic_group_open,
                           presentation([meta(syntax, delimiter)])),
                   repeat(0, unbounded, ref(arithmetic_part)),
                   literal(")", arithmetic_group_close,
                           presentation([meta(syntax, delimiter)]))])),
         rule(double_literal_dollar,
              seq([literal("$", literal_dollar,
                           presentation([meta(syntax, string)])),
                   ref(not_expansion_start)])),
         rule(command_literal_dollar,
              seq([literal("$", literal_dollar,
                           presentation([meta(syntax, command)])),
                   ref(not_expansion_start)])),
         rule(arithmetic_literal_dollar,
              seq([literal("$", literal_dollar,
                           presentation([meta(syntax, arithmetic)])),
                   ref(not_expansion_start)])),
         rule(not_expansion_start,
              not(terminal(
                      text(codepoint(union([range(65, 90), range(97, 122),
                                            range(48, 57),
                                            chars("_({*?#$!-@")]))),
                      presentation([]))))],
        [])).
