// The synthetic cell font and the forced stylesheet (DESIGN-cellulose.md C2).
//
// Every Unicode codepoint maps to an empty glyph with a fixed advance (half an
// em = one cell, or a full em = two cells for wide characters), so text laid
// out under this font lands on the terminal grid and paints no pixels — the
// screenshot then carries only non-text content. The TTF is generated by the
// prototype's `cellfont.py` and checked in as a deterministic asset.

use std::sync::OnceLock;

/// CSS pixels per terminal column / row. The font is forced to CELL_H px with
/// matching line-height, so one character advances exactly one cell.
pub const CELL_W: i64 = 8;
pub const CELL_H: i64 = 16;

/// The checked-in cell font (see `cellfont.py` in the prototype; ~9.8 KB).
pub const FONT_TTF: &[u8] = include_bytes!("cellfont.ttf");

/// `data:` URL for the font, base64'd once.
pub fn font_data_url() -> &'static str {
    static URL: OnceLock<String> = OnceLock::new();
    URL.get_or_init(|| {
        use base64::Engine as _;
        format!(
            "data:font/ttf;base64,{}",
            base64::engine::general_purpose::STANDARD.encode(FONT_TTF)
        )
    })
}

/// The stylesheet forced on every document: the cell font at a fixed size,
/// with justification / kerning / ligatures / spacing / effects flattened so
/// text layout is a plain sum of cell-multiple advances.
pub fn forced_css() -> String {
    format!(
        "@font-face {{ font-family: '__cellulose'; src: url({url}); }}\n\
         * {{\n\
           font-family: '__cellulose' !important;\n\
           font-size: {h}px !important;\n\
           line-height: {h}px !important;\n\
           letter-spacing: 0 !important;\n\
           word-spacing: 0 !important;\n\
           text-indent: 0 !important;\n\
           text-align: left !important;\n\
           text-justify: none !important;\n\
           font-kerning: none !important;\n\
           font-variant-ligatures: none !important;\n\
           font-feature-settings: normal !important;\n\
           text-shadow: none !important;\n\
           text-transform: none !important;\n\
           vertical-align: baseline !important;\n\
           animation: none !important;\n\
           transition: none !important;\n\
           scroll-behavior: auto !important;\n\
           border-radius: 0 !important;\n\
         }}",
        url = font_data_url(),
        h = CELL_H,
    )
}

/// The document-start script that injects `forced_css` into every frame,
/// retrying via a MutationObserver until `documentElement` exists.
pub fn inject_js() -> String {
    let css = serde_json::Value::String(forced_css()).to_string();
    format!(
        "(() => {{\n\
           const css = {css};\n\
           const add = () => {{\n\
             const root = document.documentElement;\n\
             if (!root) return false;\n\
             const s = document.createElement('style');\n\
             s.id = '__cellulose_style';\n\
             s.textContent = css;\n\
             root.appendChild(s);\n\
             return true;\n\
           }};\n\
           if (!add()) {{\n\
             new MutationObserver((_, obs) => {{ if (add()) obs.disconnect(); }})\n\
               .observe(document, {{ childList: true, subtree: true }});\n\
           }}\n\
         }})();"
    )
}

/// How many terminal cells a character occupies under the cell font: wide
/// (East-Asian) characters take two, everything printable takes one. Controls
/// and zero-width characters are treated as one (they are sanitized to a space
/// before placement).
pub fn char_cells(ch: char) -> usize {
    use unicode_width::UnicodeWidthChar;
    match ch.width() {
        Some(w) if w > 0 => w,
        _ => 1,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn font_asset_is_present_and_small() {
        assert!(FONT_TTF.starts_with(&[0x00, 0x01, 0x00, 0x00]) // TrueType
            || FONT_TTF.starts_with(b"OTTO"));
        assert!(FONT_TTF.len() < 100_000);
    }

    #[test]
    fn data_url_and_css_wire_together() {
        assert!(font_data_url().starts_with("data:font/ttf;base64,"));
        let css = forced_css();
        assert!(css.contains("__cellulose"));
        assert!(css.contains("font-size: 16px !important"));
        // the injection script embeds the css as a JS string literal
        assert!(inject_js().contains("__cellulose_style"));
    }

    #[test]
    fn cell_widths() {
        assert_eq!(char_cells('a'), 1);
        assert_eq!(char_cells('漢'), 2);
        assert_eq!(char_cells('🎉'), 2);
        assert_eq!(char_cells('\u{0301}'), 1); // combining acute → treated as 1
    }
}
